# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDKs
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: |
          11
          17
          21
    - name: Build with Maven
      run: mvn verify -ntp -B -Djava11.home=$JAVA_HOME_11_X64 -Djava17.home=$JAVA_HOME_17_X64
